# Generated by Django 5.0 on 2023-12-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.ImageField(upload_to='images/')),
                ('appName', models.CharField(max_length=200)),
                ('appLink', models.URLField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
