# Generated by Django 5.0 on 2023-12-28 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_appdetails_category_appdetails_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasksId', models.IntegerField()),
                ('points', models.IntegerField()),
                ('screenShot', models.ImageField(upload_to='screenshots/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.logindetails')),
            ],
        ),
    ]
