# Generated by Django 5.0 on 2023-12-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_taskdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
