# Generated by Django 5.0 on 2023-12-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_appdetails_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetails',
            name='admin',
            field=models.BooleanField(),
        ),
    ]
