# Generated by Django 5.0 on 2023-12-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_appdetails_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdetails',
            name='admin',
        ),
        migrations.AddField(
            model_name='logindetails',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
